### dùng bcrypt và PostgreSQL 
import streamlit as st
from config import APP_TITLE_EN, APP_TITLE_VI
import logging

# Thiết lập logging
logger = logging.getLogger(__name__)
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    logger.addHandler(handler)

# Danh sách ngôn ngữ hợp lệ
VALID_LANGUAGES = ["English", "Vietnamese"]

# Văn bản đa ngôn ngữ (i18n)
TEXT = {
    "English": {
        "app_title": APP_TITLE_EN,
        "login": "🔐 Login",
        "username": "Username",
        "password": "Password",
        "login_button": "Login",
        "register": "🆕 Register",
        "sec_question": "Security Question (for password reset)",
        "sec_answer": "Security Answer",
        "create_account": "Create Account",
        "reset_password": "♻️ Reset Password",
        "new_password": "New Password",
        "reset_button": "Reset Password",
        "logout": "Logout",
        "language": "Language",
        "title": "Title",
        "category": "Category",
        "instructions": "Instructions",
        "servings": "Servings",
        "name": "Name",
        "quantity": "Quantity",
        "unit": "Unit",
        "need": "Need",
        "have": "Have",
        "missing": "Missing",
        "inventory": "📦 Inventory",
        "your_stock": "Your Stock",
        "no_ingredients": "No ingredients yet.",
        "unit_tips": "Unit tips: use g, kg, ml, l, tsp, tbsp, cup, piece, pcs, lạng, chén, bát.",
        "add_ingredient": "Add New Ingredient",
        "recipes": "📖 Recipes",
        "your_recipes": "Your Recipes",
        "no_recipes": "No recipes yet.",
        "save_recipe": "Save Recipe",
        "update_recipe": "Update Recipe",
        "delete_recipe": "Delete Recipe",
        "feasibility": "✅ Feasibility & Shopping",
        "create_recipes_first": "Create recipes first.",
        "you_can_cook": "Recipe Feasibility and Shopping List",
        "none_yet": "None yet.",
        "all_available": "All ingredients available.",
        "cook": "Cook",
        "missing_something": "Missing Ingredients",
        "all_feasible": "All recipes are feasible 🎉",
        "add_to_shopping": "Add missing to Shopping List",
        "shopping_list": "🛒 Shopping List",
        "empty_list": "Your shopping list is empty.",
        "update_inventory": "Update Inventory from Shopping List",
        "purchased": "Inventory updated with purchased items.",
        "select_recipes_label": "Select recipes to proceed",
        "select_purchased": "Select purchased items",
        "sent_to_shopping": "Missing ingredients added to the shopping list.",
        "cook_success": "Cooked successfully.",
        "cook_failed": "Cooking failed.",
        "adjust_recipe": "⚖️ Adjust Recipe",
        "select_recipe": "Select Recipe",
        "adjustment_type": "Adjustment Type",
        "by_servings": "By Servings",
        "by_main_ingredient": "By Main Ingredient",
        "new_servings": "New Servings",
        "main_ingredient": "Main Ingredient",
        "new_quantity": "New Quantity",
        "spice_level": "Spice Adjustment",
        "mild": "Mild (60%)",
        "normal": "Normal (80%)",
        "rich": "Rich (100%)",
        "adjusted_recipe": "Adjusted Recipe",
        "cook_adjusted": "Cook Adjusted Recipe",
        "add_to_shopping_adjusted": "Add Missing to Shopping List",
        "adjusted_recipe_title": "Adjusted: {title}",
        "no_recipe_selected": "Please select a recipe to adjust.",
        "invalid_adjustment": "Invalid adjustment parameters.",
        "cook_adjusted_success": "Adjusted recipe '{title}' cooked successfully.",
        "cook_adjusted_failed": "Failed to cook adjusted recipe '{title}'.",
        "not_logged_in": "You must be logged in to access this page.",
        "error_title_required": "Recipe title is required.",
        "error_ingredients_required": "At least one valid ingredient (with name and positive quantity) is required.",
        "duplicate_recipe": "A recipe with this title already exists.",
        "invalid_name": "Name must contain only letters, numbers, spaces, hyphens, underscores, or single quotes.",
        "food_timeline": "🍲 Food Timeline",
        "no_entries": "No entries found for the selected filters.",
        "stats_week": "This week, you cooked {count} dishes. Most frequent: {dish}.",
        "db_error": "Database error: {error}.",
        "remove_selected": "Remove Selected Ingredients",
        "search_placeholder": "Search (e.g., dish name, tag:signature, week:N, day:YYYY-MM-DD)",
        "reset_filter": "Reset Filter",
        "no_history": "No cooking history found.",
        "username_exists": "Username already exists."
    },
    "Vietnamese": {
        "app_title": APP_TITLE_VI,
        "login": "🔐 Đăng nhập",
        "username": "Tên người dùng",
        "password": "Mật khẩu",
        "login_button": "Đăng nhập",
        "register": "🆕 Đăng ký",
        "sec_question": "Câu hỏi bảo mật (để đặt lại mật khẩu)",
        "sec_answer": "Câu trả lời bảo mật",
        "create_account": "Tạo tài khoản",
        "reset_password": "♻️ Đặt lại mật khẩu",
        "new_password": "Mật khẩu mới",
        "reset_button": "Đặt lại mật khẩu",
        "logout": "Đăng xuất",
        "language": "Ngôn ngữ",
        "title": "Tiêu đề",
        "category": "Danh mục",
        "instructions": "Hướng dẫn",
        "servings": "Khẩu phần",
        "name": "Tên",
        "quantity": "Số lượng",
        "unit": "Đơn vị",
        "need": "Cần",
        "have": "Có",
        "missing": "Thiếu",
        "inventory": "📦 Kho hàng",
        "your_stock": "Kho của bạn",
        "no_ingredients": "Chưa có nguyên liệu.",
        "unit_tips": "Mẹo đơn vị: sử dụng g, kg, ml, l, tsp, tbsp, cup, piece, cái, pcs, lạng, chén, bát.",
        "add_ingredient": "Thêm nguyên liệu mới",
        "recipes": "📖 Công thức",
        "your_recipes": "Công thức của bạn",
        "no_recipes": "Chưa có công thức nào.",
        "save_recipe": "Lưu công thức",
        "update_recipe": "Cập nhật công thức",
        "delete_recipe": "Xóa công thức",
        "feasibility": "✅ Tính khả thi & Mua sắm",
        "create_recipes_first": "Hãy tạo công thức trước.",
        "you_can_cook": "Tính khả thi công thức và Danh sách mua sắm",
        "none_yet": "Chưa có.",
        "all_available": "Tất cả nguyên liệu có sẵn.",
        "cook": "Nấu",
        "missing_something": "Thiếu nguyên liệu",
        "all_feasible": "Tất cả công thức đều khả thi 🎉",
        "add_to_shopping": "Thêm thiếu vào Danh sách mua sắm",
        "shopping_list": "🛒 Danh sách mua sắm",
        "empty_list": "Danh sách mua sắm của bạn trống.",
        "update_inventory": "Cập nhật kho từ Danh sách mua sắm",
        "purchased": "Kho đã được cập nhật với các mặt hàng đã mua.",
        "select_recipes_label": "Chọn công thức để tiếp tục",
        "select_purchased": "Chọn các mặt hàng đã mua",
        "sent_to_shopping": "Nguyên liệu thiếu đã được thêm vào danh sách mua sắm.",
        "cook_success": "Nấu thành công.",
        "cook_failed": "Nấu thất bại.",
        "adjust_recipe": "⚖️ Điều chỉnh Công thức",
        "select_recipe": "Chọn Công thức",
        "adjustment_type": "Loại Điều chỉnh",
        "by_servings": "Theo Khẩu phần",
        "by_main_ingredient": "Theo Nguyên liệu Chính",
        "new_servings": "Khẩu phần Mới",
        "main_ingredient": "Nguyên liệu Chính",
        "new_quantity": "Số lượng Mới",
        "spice_level": "Điều chỉnh Gia vị",
        "mild": "Nhạt (60%)",
        "normal": "Bình thường (80%)",
        "rich": "Đậm (100%)",
        "adjusted_recipe": "Công thức Đã Điều chỉnh",
        "cook_adjusted": "Nấu Công thức Đã Điều chỉnh",
        "add_to_shopping_adjusted": "Thêm Thiếu vào Danh sách Mua sắm",
        "adjusted_recipe_title": "Đã điều chỉnh: {title}",
        "no_recipe_selected": "Vui lòng chọn một công thức để điều chỉnh.",
        "invalid_adjustment": "Tham số điều chỉnh không hợp lệ.",
        "cook_adjusted_success": "Công thức đã điều chỉnh '{title}' được nấu thành công.",
        "cook_adjusted_failed": "Không thể nấu công thức đã điều chỉnh '{title}'.",
        "not_logged_in": "Bạn phải đăng nhập để truy cập trang này.",
        "error_title_required": "Tiêu đề công thức là bắt buộc.",
        "error_ingredients_required": "Cần ít nhất một nguyên liệu hợp lệ (có tên và số lượng dương).",
        "duplicate_recipe": "Công thức với tiêu đề này đã tồn tại.",
        "invalid_name": "Tên chỉ được chứa chữ cái, số, dấu cách, dấu gạch ngang, dấu gạch dưới hoặc dấu nháy đơn.",
        "food_timeline": "🍲 Dòng thời gian Thực phẩm",
        "no_entries": "Không tìm thấy mục nào cho bộ lọc đã chọn.",
        "stats_week": "Tuần này, bạn đã nấu {count} món. Món thường xuyên nhất: {dish}.",
        "db_error": "Lỗi cơ sở dữ liệu: {error}.",
        "remove_selected": "Xóa Các Nguyên liệu Đã Chọn",
        "search_placeholder": "Tìm kiếm (ví dụ: tên món, tag:món tủ, tuần:N, ngày:YYYY-MM-DD)",
        "reset_filter": "Đặt lại Bộ lọc",
        "no_history": "Không tìm thấy lịch sử nấu ăn.",
        "username_exists": "Tên người dùng đã tồn tại."
    }
}

def get_text(key: str) -> str:
    """Retrieve localized text based on the current language.

    Args:
        key: The key for the text to retrieve.

    Returns:
        The localized text for the given key, or the key itself if not found.
    """
    language = st.session_state.get("language", "English")
    if language not in VALID_LANGUAGES:
        logger.warning(f"Invalid language '{language}', defaulting to English")
        language = "English"
    return TEXT.get(language, TEXT["English"]).get(key, key)